#!/usr/bin/env bash
# A shell script that accept argument
if [ $# -ne 1 ]; then
  echo "Usage: $0 <username>"
  exit 1
fi
username="$1"
if ! id -u "$username" &>/dev/null; then
  echo "Error: User '$username' does not exist."
  exit 1
fi
sudo -u "$username" whoami
exit 0
