#!/bin/bash
# make this work
sed -i 's/#user www-data;/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080/' /etc/nginx/sites-available/default
if nginx -t; then
    service nginx restart
fi

