#!/bin/bash
# start nginx in 7 lines
sed -i 's/#user www-data;/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080/' /etc/nginx/sites-available/default
nginx -t
if [ $? -eq 0 ] 
then
    service nginx restart
fi

