#!/usr/bin/env bash
#Install and config Nginx
sudo apt update -y
sudo apt install nginx -y
new_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
		root /var/www/html;
	index index.html index.html index.nginx-debian.html;
	server_name _;
	add_header X-Served-By $HOSTNAME;
}
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "$new_config" > /etc
