#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5452-webs
    bind *:80
    mode http
    balance roundrobin
    server 5487-web-01 54.226.182.255:80 check
    server 5487-web-02 34.230.31.69:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
