#!/bin/bash
# make it work
apt-get update && apt-get install -y nginx
service nginx start
nginx -t 2>&1 | grep server | grep 'listen 80;' | awk '{print $2}' | sed -i "/listen 80;/c\listen 80; listen $(ip -o address show dev eth0 | awk '/inet/ {print $2}')" nginx -s reload

