#!/usr/bin/env bash
#make it work
apt-get update
apt-get install -y nginx
sed -i 's/ listen 80 default_server;/ listen 80;/g' /etc/nginx/sites-available/default
/etc/init.d/nginx start
service nginx status | grep -q "not running" && echo "nginx is not running"

