#!/usr/bin/env bash
# Check for the required number of arguments
if [ $# -lt 4 ]; then
  echo "Usage: transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Extract the script arguments
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Disable strict host key checking for scp
ssh-keyscan -H $server_ip >> ~/.ssh/known_hosts

# Transfer the file using scp with the specified parameters
scp -i $ssh_key_path $file_path $username@$server_ip:~

